# Generated by Django 5.2.7 on 2025-10-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("customer", "Customer"), ("worker", "Worker")],
                max_length=10,
                null=True,
            ),
        ),
    ]
