# Generated by Django 5.2.7 on 2025-10-05 18:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("bonus", "Bonus"),
                            ("penalty", "Penalty"),
                            ("platform_fee", "Platform Fee"),
                        ],
                        max_length=15,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Platform fee deducted from worker payment",
                        max_digits=8,
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount after platform fee deduction",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Transaction description"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, help_text="Payment method used", max_length=50
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        help_text="Unique transaction identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related assignment (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="jobs.assignment",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("upi", "UPI"),
                            ("bank_transfer", "Bank Transfer"),
                            ("wallet", "Digital Wallet"),
                            ("cash", "Cash"),
                            ("card", "Credit/Debit Card"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_gateway",
                    models.CharField(
                        blank=True, help_text="Payment gateway used", max_length=50
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, help_text="Gateway response data"
                    ),
                ),
                ("bank_reference", models.CharField(blank=True, max_length=100)),
                ("upi_id", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=20)),
                ("ifsc_code", models.CharField(blank=True, max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_details",
                        to="jobs.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="Earning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_deducted",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                ("job_category", models.CharField(blank=True, max_length=20)),
                (
                    "job_duration_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "customer_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earning_record",
                        to="jobs.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["worker", "status"], name="jobs_transa_worker__e71942_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["customer", "status"], name="jobs_transa_custome_4805ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type", "status"],
                name="jobs_transa_transac_7856b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["-created_at"], name="jobs_transa_created_99c2ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_method", "status"],
                name="jobs_paymen_payment_889c48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["-initiated_at"], name="jobs_paymen_initiat_06c65b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="earning",
            index=models.Index(
                fields=["worker", "-earned_at"], name="jobs_earnin_worker__800049_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="earning",
            index=models.Index(
                fields=["job_category"], name="jobs_earnin_job_cat_536dd7_idx"
            ),
        ),
    ]
