# Generated by Django 5.2.7 on 2025-10-05 18:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_transaction_payment_earning_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating_type",
                    models.CharField(
                        choices=[
                            ("customer_to_worker", "Customer to Worker"),
                            ("worker_to_customer", "Worker to Customer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rating from 1.0 to 5.0",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "review",
                    models.TextField(blank=True, help_text="Optional written review"),
                ),
                (
                    "quality_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quality of work/service rating",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "communication_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Communication rating",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "punctuality_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Punctuality/timeliness rating",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "professionalism_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Professionalism rating",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False, help_text="Whether the review is anonymous"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the rating is from a verified transaction",
                    ),
                ),
                (
                    "helpful_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of users who found this review helpful",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="jobs.assignment",
                    ),
                ),
                (
                    "ratee",
                    models.ForeignKey(
                        help_text="User who is receiving the rating",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        help_text="User who is giving the rating",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RatingHelpful",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpful_votes",
                        to="jobs.rating",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["ratee", "rating_type"], name="jobs_rating_ratee_i_a10468_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["rater", "rating_type"], name="jobs_rating_rater_i_83e132_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["assignment"], name="jobs_rating_assignm_1b1443_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["-created_at"], name="jobs_rating_created_2d9735_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(fields=["rating"], name="jobs_rating_rating_77ca5b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("assignment", "rater", "ratee")},
        ),
        migrations.AddIndex(
            model_name="ratinghelpful",
            index=models.Index(
                fields=["rating"], name="jobs_rating_rating__cc463e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ratinghelpful",
            index=models.Index(fields=["user"], name="jobs_rating_user_id_91ebcd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="ratinghelpful",
            unique_together={("rating", "user")},
        ),
    ]
